-- AlterTable
ALTER TABLE `Product` ADD COLUMN `thermometerPercent` INTEGER NOT NULL DEFAULT 20;

-- AlterTable
ALTER TABLE `Order` ADD COLUMN `subtotalCOP` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `Order` ADD COLUMN `shippingCOP` INTEGER NOT NULL DEFAULT 7000;
ALTER TABLE `Order` ADD COLUMN `thermometerContributionCOP` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `Order` ADD COLUMN `dataConsentAt` DATETIME(3) NULL;
ALTER TABLE `Order` ADD COLUMN `dataConsentIp` VARCHAR(191) NULL;
ALTER TABLE `Order` ADD COLUMN `confirmedAt` DATETIME(3) NULL;
